name: Build
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: "azuritten"
          password: "5710753556q"
      - name: Build and push
        if: success() && (github.ref == 'refs/heads/develop')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azuritten/kaizen_development:tasks_service
      - name: Build and push
        if: success() && (github.ref == 'refs/heads/master')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azuritten/kaizen_production:tasks_service